model_name: "meta-llama/Llama-2-7b-hf"
data_directories:
  train: "./data/train"
  validation: "./data/validation"
  test: "./data/test"
output_directory: "./models/fine-tuned-llama2"
logging_directory: "./logs"
training_arguments:
  output_dir: "./results"
  num_train_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  warmup_steps: 500
  weight_decay: 0.01
  logging_steps: 10
